#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: DEMO-SERVICE
#          uri: http://localhost:9090/
#          predicates:
#            - Path=/demo/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

